# Form implementation generated from reading ui file 'UI_MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(250, 250)
        mainWindow.setMinimumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setBold(False)
        font.setWeight(50)
        mainWindow.setFont(font)
        icon = QtGui.QIcon.fromTheme("time")
        mainWindow.setWindowIcon(icon)
        mainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, -1, 0, -1)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.time_edit_box = QtWidgets.QTimeEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(15)
        self.time_edit_box.setFont(font)
        self.time_edit_box.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.time_edit_box.setObjectName("time_edit_box")
        self.gridLayout.addWidget(self.time_edit_box, 2, 0, 1, 1)
        self.reset_timer_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.reset_timer_btn.setFont(font)
        self.reset_timer_btn.setObjectName("reset_timer_btn")
        self.gridLayout.addWidget(self.reset_timer_btn, 4, 0, 1, 1)
        self.start_timer_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.start_timer_btn.setFont(font)
        self.start_timer_btn.setObjectName("start_timer_btn")
        self.gridLayout.addWidget(self.start_timer_btn, 3, 0, 1, 1)
        self.lcd_display = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_display.setStyleSheet("background-color: #ffffff;")
        self.lcd_display.setSmallDecimalPoint(False)
        self.lcd_display.setDigitCount(8)
        self.lcd_display.setMode(QtWidgets.QLCDNumber.Mode.Dec)
        self.lcd_display.setSegmentStyle(QtWidgets.QLCDNumber.SegmentStyle.Filled)
        self.lcd_display.setProperty("value", 0.0)
        self.lcd_display.setProperty("intValue", 0)
        self.lcd_display.setObjectName("lcd_display")
        self.gridLayout.addWidget(self.lcd_display, 1, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        self.statusbar.setFont(font)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 250, 22))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Positron - Timer"))
        self.time_edit_box.setDisplayFormat(_translate("mainWindow", "mm"))
        self.reset_timer_btn.setText(_translate("mainWindow", "Reset Timer"))
        self.start_timer_btn.setText(_translate("mainWindow", "Start Timer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec())
